module.exports = {
  apps: [
    {
      name: 'blog-server',
      cwd: '/var/www/simple-hope-blog/server',
      script: 'dist/index.js',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      instances: 'max',
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: '/var/www/simple-hope-blog/server/logs/error.log',
      out_file: '/var/www/simple-hope-blog/server/logs/out.log',
      time: true,
    },
    {
      name: 'blog-web',
      cwd: '/var/www/simple-hope-blog/web/web',
      script: 'server.js',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NEXT_PUBLIC_API_URL: 'https://climberzbm.cn/api',
        API_URL: 'http://127.0.0.1:3001/api',
      },
      instances: 'max',
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    {
      name: 'blog-admin',
      cwd: '/var/www/simple-hope-blog/admin',
      script: 'npx',
      args: 'serve -s dist -l 3002',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
    },
  ],
}